version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "laurensettembrino-svc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s5rdaqysgk08"
s3_prefix = "laurensettembrino-svc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
