AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for laurensettembrino-svc

Globals:
  Function:
    Timeout: 15

Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-email/
      Handler: bootstrap
      Runtime: provided.al2023
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /send-email
            Method: POST
      Environment:
        Variables:
          FROM_ADDRESS: lauren.settembrino@gmail.com
          TO_ADDRESS: lauren.settembrino@gmail.com
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: "587"
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: LaurenSettembrino/EMAIL_PASSWORD # Make sure you omit the leading slash
    Metadata:
      BuildMethod: makefile
  SendEmailOptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-email-options/
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /send-email
            Method: OPTIONS

Outputs:
  SendEmailApi:
    Description: "API Gateway endpoint URL for Prod environment for Send Email Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-email"
  SendEmailFunction:
    Description: "Send Email Function ARN"
    Value: !GetAtt SendEmailFunction.Arn
  SendEmailFunctionIamRole:
    Description: "Implicit IAM Role created for Send Email Function"
    Value: !GetAtt SendEmailFunctionRole.Arn
